// <auto-generated />
using login_registration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace login_registration.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20180616020254_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("login_registration.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UserId");

                    b.Property<int>("WeddingId");

                    b.HasKey("GuestId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeddingId");

                    b.ToTable("guests");
                });

            modelBuilder.Entity("login_registration.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(105);

                    b.Property<bool>("HasMadeWedding");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(105);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(105);

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("login_registration.Models.Wedding", b =>
                {
                    b.Property<int>("WeddingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayDate");

                    b.Property<string>("StringDate")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.Property<string>("WedderOneName")
                        .IsRequired();

                    b.Property<string>("WedderTwoName")
                        .IsRequired();

                    b.Property<string>("address")
                        .IsRequired();

                    b.Property<DateTime>("date");

                    b.HasKey("WeddingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("login_registration.Models.Guest", b =>
                {
                    b.HasOne("login_registration.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("login_registration.Models.Wedding", "WeddingToAttend")
                        .WithMany("guests")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("login_registration.Models.Wedding", b =>
                {
                    b.HasOne("login_registration.Models.User", "user")
                        .WithOne("MyWedding")
                        .HasForeignKey("login_registration.Models.Wedding", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
