# Generated by Django 2.0.5 on 2018-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='book_author',
            name='authors',
            field=models.ManyToManyField(to='books_authors.Author'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='books',
            field=models.ManyToManyField(to='books_authors.Book'),
        ),
    ]
