# Generated by Django 2.0.5 on 2018-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_auto_20180513_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='books_authors.Book'),
        ),
        migrations.DeleteModel(
            name='book_author',
        ),
    ]
