# Generated by Django 2.0.5 on 2018-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0003_auto_20180514_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='bk', to='books_authors.Book'),
        ),
    ]
